concourse-db:
  image: postgres:9.6.2-alpine
  environment:
    POSTGRES_DB: concourse
    POSTGRES_PASSWORD: concourse_pass
    POSTGRES_USER: concourse_user
    PGDATA: /database

concourse-web:
  image: node3030/concourse
  links: [concourse-db]
  command: web
  ports: ["127.0.0.1:9090:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: "${CONCOURSE_LOGIN}"
    CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_PASSWORD}"
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: "postgres://concourse_user:concourse_pass@concourse-db:5432/concourse?sslmode=disable"

concourse-worker:
  image: node3030/concourse
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web
